# Numpy  آشنایی و کار با کتابخانه  

In [72]:
import numpy as np
#from numpy import array 

x1 = np.random.randint(10, size=6) # یک بعدی array
x2 = np.random.randint(10, size=(3, 4)) # دو بعدی array
x3 = np.random.randint(10, size=(3, 4, 5)) # سه بعدی array

In [73]:
x1

array([1, 8, 5, 5, 9, 7], dtype=int32)

In [74]:
x2

array([[5, 2, 7, 6],
       [6, 3, 1, 2],
       [5, 9, 5, 9]], dtype=int32)

In [75]:
x3

array([[[7, 9, 1, 3, 3],
        [9, 4, 2, 5, 4],
        [1, 3, 2, 9, 9],
        [8, 5, 6, 7, 1]],

       [[2, 2, 8, 2, 3],
        [5, 5, 3, 5, 1],
        [1, 4, 6, 2, 2],
        [7, 5, 1, 2, 2]],

       [[9, 2, 6, 0, 5],
        [5, 8, 8, 2, 9],
        [3, 0, 0, 9, 9],
        [8, 0, 6, 0, 2]]], dtype=int32)

In [76]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [77]:
print("dtype:", x3.dtype)

dtype: int32


In [78]:
print("itemsize:", x3.itemsize, "bytes")  # 32 bits is 4 Bytes
print("nbytes:", x3.nbytes, "bytes")  # 60 * 4

itemsize: 4 bytes
nbytes: 240 bytes


In [79]:
x1

array([1, 8, 5, 5, 9, 7], dtype=int32)

In [80]:
x1[0]

np.int32(1)

In [81]:
x1[-2]

np.int32(9)

In [82]:
x2

array([[5, 2, 7, 6],
       [6, 3, 1, 2],
       [5, 9, 5, 9]], dtype=int32)

In [83]:
x2[0, 0]

np.int32(5)

In [84]:
x2[0, 0] = 12
x2

array([[12,  2,  7,  6],
       [ 6,  3,  1,  2],
       [ 5,  9,  5,  9]], dtype=int32)

In [85]:
x1[0] = 3.14159  # x1 is int so float number convert to int
x1

array([3, 8, 5, 5, 9, 7], dtype=int32)

In [86]:
# subarray دسترسی به

In [87]:
# یک بعدی

In [88]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
x[:5]

array([0, 1, 2, 3, 4])

In [90]:
x[5:]

array([5, 6, 7, 8, 9])

In [91]:
x[4:7]

array([4, 5, 6])

In [92]:
x[::2]

array([0, 2, 4, 6, 8])

In [93]:
x[1::2]

array([1, 3, 5, 7, 9])

In [94]:
x[::-1]# تمام مقادیر برعکس می شوند

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [95]:
# چند بعدی

In [96]:
x2

array([[12,  2,  7,  6],
       [ 6,  3,  1,  2],
       [ 5,  9,  5,  9]], dtype=int32)

In [97]:
x2[:2, :3]# دو سطر، سه ستون

array([[12,  2,  7],
       [ 6,  3,  1]], dtype=int32)

In [98]:
x2[:3, ::2]# تمامی سطرها، ستون ها یکی در میان

array([[12,  7],
       [ 6,  1],
       [ 5,  5]], dtype=int32)

In [99]:
x2[::-1, ::-1] #  همه با هم برعکس

array([[ 9,  5,  9,  5],
       [ 2,  1,  3,  6],
       [ 6,  7,  2, 12]], dtype=int32)

In [100]:
print(x2[:, 0]) # اولین ستون x2

[12  6  5]


In [101]:
print(x2[0]) #  x2[0, :]  برابر با

[12  2  7  6]


In [102]:
# Reshaping of Arrays

In [103]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [104]:
x = np.array([1, 2, 3])
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [105]:
#Array Concatenation and Splitting

In [106]:
#1.Concatenation of arrays

In [135]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])
#concatenate don't add dimension

array([1, 2, 3, 3, 2, 1])

In [137]:
z = np.array([99, 99, 99])
np.concatenate([x,y,z]) #still it is an array


array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [205]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

In [146]:
np.vstack([x, grid])
#stack add dimension

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [206]:
y = np.array([[99],[99]])
y

array([[99],
       [99]])

In [207]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [113]:
#Splitting of arrays

In [149]:
x = [1, 2, 3, 9, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 7])
print(x1, x2, x3)

[1 2 3] [ 9 99  3  2] [1]


In [161]:
grid2 = np.arange(16).reshape((2, 8))
grid2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [162]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [169]:
upper, lower = np.vsplit(grid, [3])
print("rows from 0 to cutValue-1 (here is 3-1):")
print(upper)
print("rows from cutValue to the end:")
print(lower)

rows from 0 to cutValue-1 (here is 3-1):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
rows from cutValue to the end:
[[12 13 14 15]]


In [170]:
left, right = np.hsplit(grid, [1]) #just one parameter, make two output value for left and right
print(left)
print(right)

[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [173]:
firstSection, secondSection, thirdSection = np.hsplit(grid, [2,3])
print("firstSection is:","\n",firstSection)
print("secondSection:","\n",secondSection)
print("thirdSection:","\n",thirdSection)

firstSection is: 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
secondSection: 
 [[ 2]
 [ 6]
 [10]
 [14]]
thirdSection: 
 [[ 3]
 [ 7]
 [11]
 [15]]


# Numpy استفاده از عملگرها در   
Operator                       ufunc Description
+ np.add                        (e.g., 1 + 1 = 2)
- np.subtract                   (e.g., 3 - 2 = 1)
- np.negative                      (e.g., -2)
* np.multiply                   (e.g., 2 * 3 = 6)
/ np.divide                     (e.g., 3 / 2 = 1.5)
// np.floor_divide              (e.g., 3 // 2 = 1)
** np.power                     (e.g., 2 ** 3 = 8)
% np.mod                        (e.g., 9 % 4 = 1)

In [174]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)
print(-(0.5*x + 1) ** 2)
np.add(x, 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]
[-1.   -2.25 -4.   -6.25]


array([2, 3, 4, 5])

In [119]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [120]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [183]:
y= np.random.random(100)
y

array([0.28359563, 0.49295576, 0.86962477, 0.17904865, 0.49672108,
       0.34247449, 0.65264349, 0.48042757, 0.04307947, 0.29116404,
       0.48240396, 0.42610336, 0.77316573, 0.36931902, 0.19476808,
       0.47543909, 0.31069111, 0.74502059, 0.92982344, 0.31689974,
       0.56160456, 0.23147301, 0.50624097, 0.46324489, 0.04551307,
       0.14649828, 0.10090093, 0.219204  , 0.74422203, 0.42751606,
       0.86778527, 0.74218693, 0.83622121, 0.31473625, 0.24387477,
       0.41042554, 0.49054376, 0.46922212, 0.68952041, 0.33130453,
       0.18957577, 0.76973696, 0.37887338, 0.45426594, 0.64582847,
       0.65099022, 0.31638006, 0.89815147, 0.54191091, 0.19554085,
       0.71164702, 0.60272777, 0.88371066, 0.98622173, 0.02398839,
       0.31817376, 0.69708332, 0.66592793, 0.08308652, 0.06804127,
       0.55551189, 0.1813325 , 0.85915566, 0.8050625 , 0.6010827 ,
       0.11463703, 0.95651471, 0.03559289, 0.33861653, 0.60542771,
       0.52221851, 0.06307743, 0.43299834, 0.4634708 , 0.50786

In [184]:
np.min(y), np.max(y)
#y.min(), y.max() #we can use axis

(np.float64(0.013661715155823817), np.float64(0.9862217347438065))

In [186]:
M = np.random.random((3, 4))
print(M)

[[0.8881531  0.02816203 0.74646278 0.40727517]
 [0.39187643 0.3096947  0.35641232 0.65330391]
 [0.90078449 0.39620993 0.28543741 0.11910708]]


In [188]:
M.sum()

np.float64(5.482879354031786)

In [189]:
M.sum(axis=0)

array([2.18081402, 0.73406667, 1.38831252, 1.17968615])

In [190]:
M.sum(axis=1)

array([2.07005308, 1.71128737, 1.70153891])

In [192]:
print(M)
M.min(axis=0)

[[0.8881531  0.02816203 0.74646278 0.40727517]
 [0.39187643 0.3096947  0.35641232 0.65330391]
 [0.90078449 0.39620993 0.28543741 0.11910708]]


array([0.39187643, 0.02816203, 0.28543741, 0.11910708])

In [127]:
M.max(axis=1)

array([0.88564536, 0.89344521, 0.62620946])

In [128]:
# Sorting Arrays

In [197]:
x = np.array([[99, 1, 55, 3, 5],[2, 6,34,5, 5]])
np.sort(x) # x Do not change
x.sort(axis=0)  #change x, we can use axis
x

array([[ 1,  3,  5, 55, 99],
       [ 2,  5,  5,  6, 34]])

In [208]:
X = np.random.randint(0,10, (4, 8))
X

array([[7, 3, 0, 4, 3, 9, 7, 0],
       [1, 0, 2, 0, 1, 0, 3, 2],
       [2, 2, 8, 5, 0, 1, 8, 0],
       [6, 0, 6, 7, 3, 7, 5, 9]], dtype=int32)

In [209]:
# sort each column of X
np.sort(X, axis=0)

array([[1, 0, 0, 0, 0, 0, 3, 0],
       [2, 0, 2, 4, 1, 1, 5, 0],
       [6, 2, 6, 5, 3, 7, 7, 2],
       [7, 3, 8, 7, 3, 9, 8, 9]], dtype=int32)

In [210]:
# sort each row of X
np.sort(X, axis=1)

array([[0, 0, 3, 3, 4, 7, 7, 9],
       [0, 0, 0, 1, 1, 2, 2, 3],
       [0, 0, 1, 2, 2, 5, 8, 8],
       [0, 3, 5, 6, 6, 7, 7, 9]], dtype=int32)